
import { Country } from './types';

export const COUNTRIES: Country[] = [
  // --- AFRICA (Sovereign) ---
  { name: "Algeria", code: "dz", capital: "Algiers", lat: 36.75, lng: 3.06, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Angola", code: "ao", capital: "Luanda", lat: -8.84, lng: 13.23, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Benin", code: "bj", capital: "Porto-Novo", lat: 6.48, lng: 2.62, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Botswana", code: "bw", capital: "Gaborone", lat: -24.65, lng: 25.91, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Burkina Faso", code: "bf", capital: "Ouagadougou", lat: 12.37, lng: -1.53, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Burundi", code: "bi", capital: "Gitega", lat: -3.43, lng: 29.93, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Cabo Verde", code: "cv", capital: "Praia", lat: 14.92, lng: -23.51, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Cameroon", code: "cm", capital: "Yaoundé", lat: 3.85, lng: 11.52, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Central African Republic", code: "cf", capital: "Bangui", lat: 4.36, lng: 18.56, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Chad", code: "td", capital: "N'Djamena", lat: 12.11, lng: 15.04, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Comoros", code: "km", capital: "Moroni", lat: -11.7, lng: 43.25, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Congo (DRC)", code: "cd", capital: "Kinshasa", lat: -4.33, lng: 15.31, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Congo", code: "cg", capital: "Brazzaville", lat: -4.27, lng: 15.28, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Djibouti", code: "dj", capital: "Djibouti City", lat: 11.59, lng: 43.15, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Egypt", code: "eg", capital: "Cairo", lat: 30.04, lng: 31.24, continent: "Africa", difficulty: "Easy", type: "Sovereign" },
  { name: "Equatorial Guinea", code: "gq", capital: "Malabo", lat: 3.75, lng: 8.78, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Eritrea", code: "er", capital: "Asmara", lat: 15.33, lng: 38.93, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Eswatini", code: "sz", capital: "Mbabane", lat: -26.32, lng: 31.14, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Ethiopia", code: "et", capital: "Addis Ababa", lat: 9.02, lng: 38.75, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Gabon", code: "ga", capital: "Libreville", lat: 0.39, lng: 9.45, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Gambia", code: "gm", capital: "Banjul", lat: 13.45, lng: -16.58, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Ghana", code: "gh", capital: "Accra", lat: 5.56, lng: -0.2, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Guinea", code: "gn", capital: "Conakry", lat: 9.51, lng: -13.7, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Guinea-Bissau", code: "gw", capital: "Bissau", lat: 11.85, lng: -15.58, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Ivory Coast", code: "ci", capital: "Yamoussoukro", lat: 6.82, lng: -5.28, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Kenya", code: "ke", capital: "Nairobi", lat: -1.28, lng: 36.82, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Lesotho", code: "ls", capital: "Maseru", lat: -29.32, lng: 27.48, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Liberia", code: "lr", capital: "Monrovia", lat: 6.31, lng: -10.8, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Libya", code: "ly", capital: "Tripoli", lat: 32.89, lng: 13.18, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Madagascar", code: "mg", capital: "Antananarivo", lat: -18.91, lng: 47.53, continent: "Africa", difficulty: "Easy", type: "Sovereign" },
  { name: "Malawi", code: "mw", capital: "Lilongwe", lat: -13.97, lng: 33.77, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Mali", code: "ml", capital: "Bamako", lat: 12.65, lng: -8.0, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Mauritania", code: "mr", capital: "Nouakchott", lat: 18.09, lng: -15.98, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Mauritius", code: "mu", capital: "Port Louis", lat: -20.16, lng: 57.51, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Morocco", code: "ma", capital: "Rabat", lat: 34.01, lng: -6.83, continent: "Africa", difficulty: "Easy", type: "Sovereign" },
  { name: "Mozambique", code: "mz", capital: "Maputo", lat: -25.97, lng: 32.58, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Namibia", code: "na", capital: "Windhoek", lat: -22.56, lng: 17.08, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Niger", code: "ne", capital: "Niamey", lat: 13.51, lng: 2.11, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Nigeria", code: "ng", capital: "Abuja", lat: 9.06, lng: 7.49, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Rwanda", code: "rw", capital: "Kigali", lat: -1.94, lng: 30.06, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Sao Tome and Principe", code: "st", capital: "São Tomé", lat: 0.34, lng: 6.73, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Senegal", code: "sn", capital: "Dakar", lat: 14.69, lng: -17.44, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Seychelles", code: "sc", capital: "Victoria", lat: -4.62, lng: 55.45, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Sierra Leone", code: "sl", capital: "Freetown", lat: 8.48, lng: -13.23, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Somalia", code: "so", capital: "Mogadishu", lat: 2.04, lng: 45.34, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "South Africa", code: "za", capital: "Pretoria", lat: -25.75, lng: 28.19, continent: "Africa", difficulty: "Easy", type: "Sovereign" },
  { name: "South Sudan", code: "ss", capital: "Juba", lat: 4.85, lng: 31.62, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Sudan", code: "sd", capital: "Khartoum", lat: 15.5, lng: 32.56, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Tanzania", code: "tz", capital: "Dodoma", lat: -6.17, lng: 35.75, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Togo", code: "tg", capital: "Lomé", lat: 6.14, lng: 1.22, continent: "Africa", difficulty: "Hard", type: "Sovereign" },
  { name: "Tunisia", code: "tn", capital: "Tunis", lat: 36.81, lng: 10.17, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Uganda", code: "ug", capital: "Kampala", lat: 0.31, lng: 32.58, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Zambia", code: "zm", capital: "Lusaka", lat: -15.42, lng: 28.28, continent: "Africa", difficulty: "Normal", type: "Sovereign" },
  { name: "Zimbabwe", code: "zw", capital: "Harare", lat: -17.83, lng: 31.05, continent: "Africa", difficulty: "Normal", type: "Sovereign" },

  // --- AMERICAS (Sovereign) ---
  { name: "Antigua and Barbuda", code: "ag", capital: "St. John's", lat: 17.12, lng: -61.85, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Argentina", code: "ar", capital: "Buenos Aires", lat: -34.6, lng: -58.38, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Bahamas", code: "bs", capital: "Nassau", lat: 25.08, lng: -77.35, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Barbados", code: "bb", capital: "Bridgetown", lat: 13.1, lng: -59.6, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Belize", code: "bz", capital: "Belmopan", lat: 17.25, lng: -88.77, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Bolivia", code: "bo", capital: "Sucre", lat: -19.03, lng: -65.26, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Brazil", code: "br", capital: "Brasília", lat: -15.78, lng: -47.93, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Canada", code: "ca", capital: "Ottawa", lat: 45.42, lng: -75.7, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Chile", code: "cl", capital: "Santiago", lat: -33.45, lng: -70.67, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Colombia", code: "co", capital: "Bogotá", lat: 4.61, lng: -74.08, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Costa Rica", code: "cr", capital: "San José", lat: 9.93, lng: -84.08, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Cuba", code: "cu", capital: "Havana", lat: 23.13, lng: -82.37, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Dominica", code: "dm", capital: "Roseau", lat: 15.3, lng: -61.38, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Dominican Republic", code: "do", capital: "Santo Domingo", lat: 18.47, lng: -69.89, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Ecuador", code: "ec", capital: "Quito", lat: -0.23, lng: -78.52, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "El Salvador", code: "sv", capital: "San Salvador", lat: 13.69, lng: -89.19, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Grenada", code: "gd", capital: "St. George's", lat: 12.05, lng: -61.75, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Guatemala", code: "gt", capital: "Guatemala City", lat: 14.62, lng: -90.53, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Guyana", code: "gy", capital: "Georgetown", lat: 6.8, lng: -58.16, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Haiti", code: "ht", capital: "Port-au-Prince", lat: 18.54, lng: -72.34, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Honduras", code: "hn", capital: "Tegucigalpa", lat: 14.08, lng: -87.21, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Jamaica", code: "jm", capital: "Kingston", lat: 17.98, lng: -76.8, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Mexico", code: "mx", capital: "Mexico City", lat: 19.43, lng: -99.13, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Nicaragua", code: "ni", capital: "Managua", lat: 12.13, lng: -86.25, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Panama", code: "pa", capital: "Panama City", lat: 8.98, lng: -79.52, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Paraguay", code: "py", capital: "Asunción", lat: -25.26, lng: -57.58, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Peru", code: "pe", capital: "Lima", lat: -12.04, lng: -77.04, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Saint Kitts and Nevis", code: "kn", capital: "Basseterre", lat: 17.3, lng: -62.72, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Saint Lucia", code: "lc", capital: "Castries", lat: 14.02, lng: -61, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Saint Vincent and the Grenadines", code: "vc", capital: "Kingstown", lat: 13.15, lng: -61.22, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Suriname", code: "sr", capital: "Paramaribo", lat: 5.83, lng: -55.17, continent: "Americas", difficulty: "Hard", type: "Sovereign" },
  { name: "Trinidad and Tobago", code: "tt", capital: "Port of Spain", lat: 10.65, lng: -61.52, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "United States", code: "us", capital: "Washington, D.C.", lat: 38.91, lng: -77.04, continent: "Americas", difficulty: "Easy", type: "Sovereign" },
  { name: "Uruguay", code: "uy", capital: "Montevideo", lat: -34.9, lng: -56.16, continent: "Americas", difficulty: "Normal", type: "Sovereign" },
  { name: "Venezuela", code: "ve", capital: "Caracas", lat: 10.48, lng: -66.9, continent: "Americas", difficulty: "Normal", type: "Sovereign" },

  // --- ASIA (Sovereign) ---
  { name: "Afghanistan", code: "af", capital: "Kabul", lat: 34.53, lng: 69.17, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Armenia", code: "am", capital: "Yerevan", lat: 40.18, lng: 44.51, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Azerbaijan", code: "az", capital: "Baku", lat: 40.38, lng: 49.87, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Bahrain", code: "bh", capital: "Manama", lat: 26.22, lng: 50.58, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "Bangladesh", code: "bd", capital: "Dhaka", lat: 23.71, lng: 90.41, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Bhutan", code: "bt", capital: "Thimphu", lat: 27.47, lng: 89.64, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "Brunei", code: "bn", capital: "Bandar Seri Begawan", lat: 4.89, lng: 114.93, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "Cambodia", code: "kh", capital: "Phnom Penh", lat: 11.56, lng: 104.92, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "China", code: "cn", capital: "Beijing", lat: 39.9, lng: 116.4, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Georgia", code: "ge", capital: "Tbilisi", lat: 41.72, lng: 44.79, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "India", code: "in", capital: "New Delhi", lat: 28.61, lng: 77.21, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Indonesia", code: "id", capital: "Jakarta", lat: -6.21, lng: 106.85, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Iran", code: "ir", capital: "Tehran", lat: 35.69, lng: 51.39, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Iraq", code: "iq", capital: "Baghdad", lat: 33.34, lng: 44.4, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Israel", code: "il", capital: "Jerusalem", lat: 31.77, lng: 35.21, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Japan", code: "jp", capital: "Tokyo", lat: 35.69, lng: 139.69, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Jordan", code: "jo", capital: "Amman", lat: 31.95, lng: 35.93, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Kazakhstan", code: "kz", capital: "Astana", lat: 51.18, lng: 71.45, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Kuwait", code: "kw", capital: "Kuwait City", lat: 29.37, lng: 47.98, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Kyrgyzstan", code: "kg", capital: "Bishkek", lat: 42.87, lng: 74.59, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Laos", code: "la", capital: "Vientiane", lat: 17.97, lng: 102.63, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Lebanon", code: "lb", capital: "Beirut", lat: 33.89, lng: 35.5, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Malaysia", code: "my", capital: "Kuala Lumpur", lat: 3.14, lng: 101.69, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Maldives", code: "mv", capital: "Malé", lat: 4.17, lng: 73.51, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "Mongolia", code: "mn", capital: "Ulaanbaatar", lat: 47.91, lng: 106.92, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Myanmar", code: "mm", capital: "Naypyidaw", lat: 19.75, lng: 96.1, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Nepal", code: "np", capital: "Kathmandu", lat: 27.7, lng: 85.32, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Oman", code: "om", capital: "Muscat", lat: 23.61, lng: 58.59, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Pakistan", code: "pk", capital: "Islamabad", lat: 33.68, lng: 73.04, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Palestine", code: "ps", capital: "Jerusalem", lat: 31.77, lng: 35.23, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Philippines", code: "ph", capital: "Manila", lat: 14.6, lng: 120.98, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Qatar", code: "qa", capital: "Doha", lat: 25.29, lng: 51.53, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Saudi Arabia", code: "sa", capital: "Riyadh", lat: 24.71, lng: 46.68, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Singapore", code: "sg", capital: "Singapore", lat: 1.29, lng: 103.85, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "South Korea", code: "kr", capital: "Seoul", lat: 37.57, lng: 126.98, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "North Korea", code: "kp", capital: "Pyongyang", lat: 39.03, lng: 125.75, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Sri Lanka", code: "lk", capital: "Sri Jayawardenepura Kotte", lat: 6.89, lng: 79.9, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Syria", code: "sy", capital: "Damascus", lat: 33.51, lng: 36.28, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Tajikistan", code: "tj", capital: "Dushanbe", lat: 38.54, lng: 68.78, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Thailand", code: "th", capital: "Bangkok", lat: 13.76, lng: 100.5, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Timor-Leste", code: "tl", capital: "Dili", lat: -8.56, lng: 125.56, continent: "Asia", difficulty: "Hard", type: "Sovereign" },
  { name: "Turkey", code: "tr", capital: "Ankara", lat: 39.93, lng: 32.85, continent: "Asia", difficulty: "Easy", type: "Sovereign" },
  { name: "Turkmenistan", code: "tm", capital: "Ashgabat", lat: 37.96, lng: 58.33, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "United Arab Emirates", code: "ae", capital: "Abu Dhabi", lat: 24.47, lng: 54.37, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Uzbekistan", code: "uz", capital: "Tashkent", lat: 41.3, lng: 69.24, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Vietnam", code: "vn", capital: "Hanoi", lat: 21.03, lng: 105.83, continent: "Asia", difficulty: "Normal", type: "Sovereign" },
  { name: "Yemen", code: "ye", capital: "Sana'a", lat: 15.35, lng: 44.21, continent: "Asia", difficulty: "Normal", type: "Sovereign" },

  // --- EUROPE (Sovereign) ---
  { name: "Albania", code: "al", capital: "Tirana", lat: 41.33, lng: 19.82, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Andorra", code: "ad", capital: "Andorra la Vella", lat: 42.5, lng: 1.52, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Austria", code: "at", capital: "Vienna", lat: 48.21, lng: 16.37, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Belarus", code: "by", capital: "Minsk", lat: 53.9, lng: 27.57, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Belgium", code: "be", capital: "Brussels", lat: 50.85, lng: 4.35, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Bosnia and Herzegovina", code: "ba", capital: "Sarajevo", lat: 43.85, lng: 18.36, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Bulgaria", code: "bg", capital: "Sofia", lat: 42.7, lng: 23.32, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Croatia", code: "hr", capital: "Zagreb", lat: 45.81, lng: 15.98, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Cyprus", code: "cy", capital: "Nicosia", lat: 35.17, lng: 33.37, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Czech Republic", code: "cz", capital: "Prague", lat: 50.08, lng: 14.44, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Denmark", code: "dk", capital: "Copenhagen", lat: 55.68, lng: 12.57, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Estonia", code: "ee", capital: "Tallinn", lat: 59.44, lng: 24.75, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Finland", code: "fi", capital: "Helsinki", lat: 60.17, lng: 24.94, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "France", code: "fr", capital: "Paris", lat: 48.86, lng: 2.35, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Germany", code: "de", capital: "Berlin", lat: 52.52, lng: 13.4, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Greece", code: "gr", capital: "Athens", lat: 37.98, lng: 23.73, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Hungary", code: "hu", capital: "Budapest", lat: 47.5, lng: 19.04, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Iceland", code: "is", capital: "Reykjavík", lat: 64.14, lng: -21.9, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Ireland", code: "ie", capital: "Dublin", lat: 53.33, lng: -6.25, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Italy", code: "it", capital: "Rome", lat: 41.89, lng: 12.48, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Latvia", code: "lv", capital: "Riga", lat: 56.95, lng: 24.11, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Liechtenstein", code: "li", capital: "Vaduz", lat: 47.14, lng: 9.52, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Lithuania", code: "lt", capital: "Vilnius", lat: 54.68, lng: 25.28, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Luxembourg", code: "lu", capital: "Luxembourg City", lat: 49.61, lng: 6.13, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Malta", code: "mt", capital: "Valletta", lat: 35.9, lng: 14.51, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Moldova", code: "md", capital: "Chisinau", lat: 47.01, lng: 28.86, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Monaco", code: "mc", capital: "Monaco", lat: 43.73, lng: 7.42, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Montenegro", code: "me", capital: "Podgorica", lat: 42.44, lng: 19.26, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Netherlands", code: "nl", capital: "Amsterdam", lat: 52.37, lng: 4.89, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "North Macedonia", code: "mk", capital: "Skopje", lat: 42.0, lng: 21.43, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Norway", code: "no", capital: "Oslo", lat: 59.91, lng: 10.75, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Poland", code: "pl", capital: "Warsaw", lat: 52.23, lng: 21.01, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Portugal", code: "pt", capital: "Lisbon", lat: 38.72, lng: -9.14, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Romania", code: "ro", capital: "Bucharest", lat: 44.43, lng: 26.1, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Russia", code: "ru", capital: "Moscow", lat: 55.75, lng: 37.62, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "San Marino", code: "sm", capital: "San Marino", lat: 43.94, lng: 12.45, continent: "Europe", difficulty: "Hard", type: "Sovereign" },
  { name: "Serbia", code: "rs", capital: "Belgrade", lat: 44.79, lng: 20.45, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Slovakia", code: "sk", capital: "Bratislava", lat: 48.15, lng: 17.11, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Slovenia", code: "si", capital: "Ljubljana", lat: 46.05, lng: 14.51, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Spain", code: "es", capital: "Madrid", lat: 40.42, lng: -3.7, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Sweden", code: "se", capital: "Stockholm", lat: 59.33, lng: 18.06, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Switzerland", code: "ch", capital: "Bern", lat: 46.95, lng: 7.45, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "Ukraine", code: "ua", capital: "Kyiv", lat: 50.45, lng: 30.52, continent: "Europe", difficulty: "Normal", type: "Sovereign" },
  { name: "United Kingdom", code: "gb", capital: "London", lat: 51.51, lng: -0.13, continent: "Europe", difficulty: "Easy", type: "Sovereign" },
  { name: "Vatican City", code: "va", capital: "Vatican City", lat: 41.9, lng: 12.45, continent: "Europe", difficulty: "Hard", type: "Sovereign" },

  // --- OCEANIA (Sovereign) ---
  { name: "Australia", code: "au", capital: "Canberra", lat: -35.28, lng: 149.13, continent: "Oceania", difficulty: "Easy", type: "Sovereign" },
  { name: "Fiji", code: "fj", capital: "Suva", lat: -18.14, lng: 178.44, continent: "Oceania", difficulty: "Normal", type: "Sovereign" },
  { name: "Kiribati", code: "ki", capital: "South Tarawa", lat: 1.33, lng: 173, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Marshall Islands", code: "mh", capital: "Majuro", lat: 7.09, lng: 171.38, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Micronesia", code: "fm", capital: "Palikir", lat: 6.92, lng: 158.16, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Nauru", code: "nr", capital: "Yaren", lat: -0.55, lng: 166.92, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "New Zealand", code: "nz", capital: "Wellington", lat: -41.29, lng: 174.78, continent: "Oceania", difficulty: "Easy", type: "Sovereign" },
  { name: "Palau", code: "pw", capital: "Ngerulmud", lat: 7.5, lng: 134.62, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Papua New Guinea", code: "pg", capital: "Port Moresby", lat: -9.44, lng: 147.18, continent: "Oceania", difficulty: "Normal", type: "Sovereign" },
  { name: "Samoa", code: "ws", capital: "Apia", lat: -13.83, lng: -171.76, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Solomon Islands", code: "sb", capital: "Honiara", lat: -9.43, lng: 159.95, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Tonga", code: "to", capital: "Nukuʻalofa", lat: -21.14, lng: -175.2, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Tuvalu", code: "tv", capital: "Funafuti", lat: -8.52, lng: 179.19, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },
  { name: "Vanuatu", code: "vu", capital: "Port Vila", lat: -17.73, lng: 168.32, continent: "Oceania", difficulty: "Hard", type: "Sovereign" },

  // --- TERRITORIES & UNRECOGNIZED (The specialized mode pool) ---
  { name: "Taiwan", code: "tw", capital: "Taipei", lat: 25.03, lng: 121.57, continent: "Asia", difficulty: "Easy", type: "Territory" },
  { name: "Kosovo", code: "xk", capital: "Pristina", lat: 42.66, lng: 21.16, continent: "Europe", difficulty: "Normal", type: "Territory" },
  { name: "Greenland", code: "gl", capital: "Nuuk", lat: 64.18, lng: -51.72, continent: "Americas", difficulty: "Easy", type: "Territory" },
  { name: "Puerto Rico", code: "pr", capital: "San Juan", lat: 18.46, lng: -66.1, continent: "Americas", difficulty: "Normal", type: "Territory" },
  { name: "Hong Kong", code: "hk", capital: "Hong Kong", lat: 22.3, lng: 114.2, continent: "Asia", difficulty: "Normal", type: "Territory" },
  { name: "Macau", code: "mo", capital: "Macau", lat: 22.16, lng: 113.54, continent: "Asia", difficulty: "Hard", type: "Territory" },
  { name: "Western Sahara", code: "eh", capital: "Laayoune", lat: 27.15, lng: -13.2, continent: "Africa", difficulty: "Hard", type: "Territory" },
  { name: "Falkland Islands", code: "fk", capital: "Stanley", lat: -51.7, lng: -57.85, continent: "Americas", difficulty: "Hard", type: "Territory" },
  { name: "Faroe Islands", code: "fo", capital: "Tórshavn", lat: 62.01, lng: -6.77, continent: "Europe", difficulty: "Hard", type: "Territory" },
  { name: "Gibraltar", code: "gi", capital: "Gibraltar", lat: 36.14, lng: -5.35, continent: "Europe", difficulty: "Hard", type: "Territory" },
  { name: "Guam", code: "gu", capital: "Hagåtña", lat: 13.48, lng: 144.75, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "New Caledonia", code: "nc", capital: "Nouméa", lat: -22.27, lng: 166.45, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "French Polynesia", code: "pf", capital: "Papeete", lat: -17.54, lng: -149.57, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "Bermuda", code: "bm", capital: "Hamilton", lat: 32.29, lng: -64.78, continent: "Americas", difficulty: "Hard", type: "Territory" },
  { name: "Cayman Islands", code: "ky", capital: "George Town", lat: 19.3, lng: -81.38, continent: "Americas", difficulty: "Hard", type: "Territory" },
  { name: "Cook Islands", code: "ck", capital: "Avarua", lat: -21.2, lng: -159.77, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "Niue", code: "nu", capital: "Alofi", lat: -19.05, lng: -169.92, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "American Samoa", code: "as", capital: "Pago Pago", lat: -14.27, lng: -170.7, continent: "Oceania", difficulty: "Hard", type: "Territory" },
  { name: "British Virgin Islands", code: "vg", capital: "Road Town", lat: 18.42, lng: -64.62, continent: "Americas", difficulty: "Hard", type: "Territory" },
  { name: "Isle of Man", code: "im", capital: "Douglas", lat: 54.15, lng: -4.48, continent: "Europe", difficulty: "Hard", type: "Territory" },
  { name: "Jersey", code: "je", capital: "Saint Helier", lat: 49.19, lng: -2.1, continent: "Europe", difficulty: "Hard", type: "Territory" },
  { name: "Guernsey", code: "gg", capital: "Saint Peter Port", lat: 49.46, lng: -2.54, continent: "Europe", difficulty: "Hard", type: "Territory" }
];

export const MAX_GUESSES = 6;
